spring:
  application:
    name: order-service
<<<<<<< HEAD
  rabbitmq:
    host: 192.168.186.137
    port: 5672
    username: admin
    password: admin
=======
>>>>>>> refs/remotes/origin/master
    
server:
  port: 8201  
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
